---
title: "Inverse Transform Method"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

## Exponential distribution

```{r}
expo <- function(lambda){
  u <-runif(1)
  s <- -log(1-u)/lambda
}
```

```{r}
n <- 1000
lambda <- 3

sample <- vector(length = n)

for (i in 1:n){
  sample[i] <- expo(lambda)
}

hist(sample)

```

## Triangular

```{r}
trian <- function(){
  u <- runif(1)
  if (u <= 0.5){
    s <- sqrt(2*u)
  }
  else{
    s <- (4-sqrt(8-8*u))/2
  }
}
```

```{r}
n <- 1000

sample <- vector(length = n)

for (i in 1:n){
  sample[i] <- trian()
}

hist(sample)
```

# Rejection Sampling

```{r}
curve((3/2)*x^3+(11/8)*x^2+(1/6)*x+(1/12), 0, 1)
abline(a = 3.125, b = 0)


n <- 5000

U <- runif(n)
X <- runif(n)

pi_fun <- function(x) {
  new_x = (3/2)*(x^3)+(11/8)*(x^2)+(1/6)*(x)+(1/12)
  return(new_x)
}

count <- 1
accepted_samples <- c()

while(count <= n & length(accepted_samples) < 1000){
  test_u = U[count]
  test_x = pi_fun(X[count])/(3.125*dunif(X[count],0,1))
  if (test_u <= test_x){
    accepted_samples = rbind(accepted_samples, X[count])
    count = count + 1
  }
  count = count + 1
}

hist(accepted_samples)

```


